// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(TrtaContext))]
    [Migration("20221205154047_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("web.Models.Odkup", b =>
                {
                    b.Property<int>("OdkupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdkupId"), 1L, 1);

                    b.Property<decimal>("CenaNaKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PridelekId")
                        .HasColumnType("int");

                    b.Property<int>("letoMeritve")
                        .HasColumnType("int");

                    b.HasKey("OdkupId");

                    b.ToTable("Odkup", (string)null);
                });

            modelBuilder.Entity("web.Models.Pridelek", b =>
                {
                    b.Property<int>("PridelekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PridelekId"), 1L, 1);

                    b.Property<decimal>("KgNaTrto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KolNaHa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("TrteId")
                        .HasColumnType("int");

                    b.Property<int>("VinogradId")
                        .HasColumnType("int");

                    b.Property<int?>("VinogradiId")
                        .HasColumnType("int");

                    b.Property<int>("letoMeritve")
                        .HasColumnType("int");

                    b.HasKey("PridelekId");

                    b.HasIndex("TrteId");

                    b.HasIndex("VinogradiId");

                    b.ToTable("Pridelek", (string)null);
                });

            modelBuilder.Entity("web.Models.Trte", b =>
                {
                    b.Property<int>("TrteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrteId"), 1L, 1);

                    b.Property<string>("Sorta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrteId");

                    b.ToTable("Trte", (string)null);
                });

            modelBuilder.Entity("web.Models.Vinogradi", b =>
                {
                    b.Property<int>("VinogradiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VinogradiId"), 1L, 1);

                    b.Property<int>("Povrsina")
                        .HasColumnType("int");

                    b.Property<int>("StTrt")
                        .HasColumnType("int");

                    b.Property<int>("TrteId")
                        .HasColumnType("int");

                    b.Property<int>("letoMeritve")
                        .HasColumnType("int");

                    b.HasKey("VinogradiId");

                    b.HasIndex("TrteId");

                    b.ToTable("Vinogradi", (string)null);
                });

            modelBuilder.Entity("web.Models.Pridelek", b =>
                {
                    b.HasOne("web.Models.Trte", "Trte")
                        .WithMany("Pridelek")
                        .HasForeignKey("TrteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Models.Vinogradi", "Vinogradi")
                        .WithMany("Pridelek")
                        .HasForeignKey("VinogradiId");

                    b.Navigation("Trte");

                    b.Navigation("Vinogradi");
                });

            modelBuilder.Entity("web.Models.Vinogradi", b =>
                {
                    b.HasOne("web.Models.Trte", "Trte")
                        .WithMany("Vinogradi")
                        .HasForeignKey("TrteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trte");
                });

            modelBuilder.Entity("web.Models.Trte", b =>
                {
                    b.Navigation("Pridelek");

                    b.Navigation("Vinogradi");
                });

            modelBuilder.Entity("web.Models.Vinogradi", b =>
                {
                    b.Navigation("Pridelek");
                });
#pragma warning restore 612, 618
        }
    }
}
